# Generated by Django 5.0.2 on 2024-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_bio_profile_tiktokurl_profile_youtubeurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shapka',
            field=models.ImageField(blank=True, upload_to='shapki/'),
        ),
    ]
